### ISSUE TITLE
Runge kutta integrators

### ISSUE THREAD

**Issue by Jumarulanda** [Jumarulanda/cufico2_parcial3#1]
Add runge-kutta integrator header with features:
- Integrator class of each runge-kutta order (4,6,8).
- Each class has methods to change integration parameters (time step)
- Integration method accepts as first input the right hand side of the first order differential equations
- Integration method accepts as second input the initial conditions in the same order as the differential equation system
- Integration method accepts as third input the integration range
- Integration method accepts as fourth input additional parameters to the differential equation system (dont know if this is possible)
- Integration method returns (or prints. or saves in a file) an array of size [ T_steps , # of dependent vars + independen var] where each entry is another array that contains the values of the variables of the system at each time-step

**Comment by maryialejandra** [comment]
I have a question about the third item: do you mean a function with the first-order differential equation? or a vector? or what? 
In our case, we need a system of two first-order differential equations...

**Comment by Jumarulanda** [comment]
> I have a question about the third item: do you mean a function with the first-order differential equation? or a vector? or what?
> In our case, we need a system of two first-order differential equations...

This integration method is for general purposes so that it can be coupled easy with the whole code. We are using a system that results in two first-order ODEs, so this input vector would only have two entries. Given a system of first-order ODE given as

y_1'(x) = f1(x)

y_2'(x) = f2(x)

y_3'(x) = f3(x)

Then the input vector would be

{f1, f2, f3}
